### ISSUE TITLE
Is there any risk of it deleting messages? 

### ISSUE THREAD

**Issue by LennyPenny** [codefeathers/WhatsDown#1]
Hey, 
I really love the idea of this (I still hang onto all the messages I ever wrote on whatsapp copying everything over manually)

Since this is still in development - is there any risk of this messing up my messages?

**Comment by MKRhere** [comment]
Hi Lenny,

There is no risk at all with my approach. I passively record messages that are opened on WhatsApp Web, and store them in a local database that is on your computer. You could backup this local database if you want. There are no extra requests sent to WhatsApp itself.

Only a small caveat—only messages that are opened with `WhatsApp Web` in a browser will be recorded. If it was not seen in the browser (if there are older messages on your mobile for example), it will not be recorded. Also the current state of this project does not work. The Chrome extension simply logs messages to console.

**Comment by LennyPenny** [comment]
okay that sounds great! 

Awesome job so far :)

**Comment by MKRhere** [comment]
Awesome. I'll try to put in more commits in January. Do watch the repo if interested :)
